# Use the official Python image from the Docker Hub
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Run migrations
RUN python manage.py migrate

# Start the application
CMD ["gunicorn", "server.wsgi:application", "--bind", "0.0.0.0:8000"]