# Generated by Django 5.1.2 on 2025-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='org_url',
            field=models.CharField(max_length=256),
        ),
    ]
