# Generated by Django 5.1.2 on 2025-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortly', '0002_alter_shorturl_org_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='org_url',
            field=models.CharField(max_length=500),
        ),
    ]
